### ISSUE TITLE
Compile for 22.04 fails at 3_build_libs.sh

### ISSUE THREAD

**Issue by rezbagoly122** [ag1455/OpenPLi-PC_Python3#2]
I used a clean install of Ubuntu 22.04 (original, no subversions) . When running the script the subscript "build and install gst-plugin-dvbmediasink" cut the link between /usr/lib and /lib. It causes the compilation to stop, and when rebooting kernel panik.
Failing to boot can be corrected by running the live cd/usb and restoring the link. No need to run the procedure described in the previous (closed) report. However the problem of running the script remains.
Can you give me a hint how to proceed with this?

**Comment by ag1455** [comment]
This problem exists, but it is extremely rare. Perhaps this is a shell failure in case the library cannot be downloaded. I don't see any obvious reason.
I manually removed all packages from the libs folder and try to remove all words:
--autodoinst=yes
Without this, packages will be also installed. 
Perhaps I need to come up with a way to protect the ~lib link from being erased.

**Comment by rezbagoly122** [comment]
Thanks for the answere. Unfortunately, removing --autodoinst=yes did not help, however it was not a fresh install. Tomorrow I wil start it again with a fresh install. Thanx anyway.

**Comment by rezbagoly122** [comment]
FYI I tried to compile on a Q1900M-Pro3 (intel-atom) board.

**Comment by rezbagoly122** [comment]
On that board with fresh install the new version of 3_build_libs.sh also fails, at # Build and install gst-plugin-subsink-git:.
It seem that there is one step ahead.

**Comment by rezbagoly122** [comment]
I tried to compile the new version on a different motherboard A68N-2100K. The problem still exits, the ~lib link is still cut at building gst-plugin-dvbmediasink. I know these are ancient boards, but I did not want to make my working system useless. Sorry, until a solution can be found, I think, I will return to 2.7 since I had successful compile with that.

**Comment by ag1455** [comment]
Try to remove "install=yes". Then print "dpkg -i *deb". Maybe need to
check HDD/SDD or SATA connector.

вт, 20 июн. 2023 г., 18:12 rezbagoly122 ***@***.***>:

**Comment by ag1455** [comment]
I tested the current commit on a similar "Foxconn D52S" motherboard and found no problem. Of course, this motherboard is rather weak for E2PC and there is no HDMI, but it works.

**Comment by rezbagoly122** [comment]
I returned to the original Q1900M board (it's stronger), and restarted 
fresh, copied and commented out the original "checkinstall" line, from 
the copy I removed "--install=yes", and run it again. Same issue. 
Checking libs, The gst-plugin-dvb-mediasink lib exists. I am trying to 
run it separately, and see what happens. Thanks for helping me.

**Comment by rezbagoly122** [comment]
The traditional way (./configure, make, make install) does not break the 
link and installs to the /usr/local/lib/gstreamer-1.0 lib. However I do 
not no if it is the right place.

**Comment by ag1455** [comment]
You can use --configure=/usr/local in the script. This path must be in
/etc/ld.so.conf.d.
Any filename. Then "ldconfig".

ср, 21 июн. 2023 г., 16:26 rezbagoly122 ***@***.***>:

**Comment by ag1455** [comment]
prefix=/usr/local

ср, 21 июн. 2023 г., 16:45 ТелеБездельник в отставке ***@***.***>:

**Comment by rezbagoly122** [comment]
It seems that the "--with-dtsdownmix" causes the problem. It complains about missing dca.h. without that it compiles and doesn't break the link, and I didn't  even left out "install=yes". Installing libdca-dev seems to solve the problem, however it sucks that it also breaks the lib link. Thanks for all your help. The installation scripts succeded.
